db:
 host: "bxvqsy7lekm9kryivmvl-mysql.services.clever-cloud.com"
 port: "3306"
 user: "![6jFESSuFzhdSDv0ta6v8ghqA0yI+bGVI]"
 password: "![85lYB1sBTWS04MGeMyg6dEt08+thwxYB]"
 database: "![ncRa3rtr0oY3HzJ8Em9aC21wOk3RsODN]"
 