#%RAML 1.0 NamedExample
  {
customerStatusRequest
 : {
contactType : text,
countryCode : + 91,
mobile : 7647678765,
email: kumar@gmail.com ,
password : sdkhjfd,
acceptDataPolicy : true ,
status : true
}
}
