#%RAML 1.0 NamedExample
"msg": "failure operation"
"code": 401
"success": false
"eventId": "dbfhjsdbhfbdo8ryt876t75ty"
"error": 
    "type": "UNAUTHORIZED"
    "title": "Un Autherized error"
    "details": "Autherization failure"
