#%RAML 1.0 DataType
type: object
properties:
  customerStatusRequest:
    type: object
    properties:
      contactType: string
      countryCode?: string
      mobile?: string
      email?: string
      password: string
      status: boolean
        

  