#%RAML 1.0
title:  Customers Experience API
description: This API will create new customer.

traits:
  header: !include /exchange_modules/c1dfddf1-bc06-4261-bf9f-7e573d7c6f9f/header_eapi/1.0.6/header_eapi.raml
types:
  Customerrequest: !include /Datatypes/CustomerdataType.raml
  CustomerResponse: !include /Datatypes/CustomerresponsedataType.raml
/customers:
  is:
    - header
  post:
    description: This API will create new customer 
    body:
     application/json:
       examples: !include /Example/Customerexample.raml
        
    responses:
      200:
        body:
         application/json:
          examples: !include /Example/Responseexample.raml