#%RAML 1.0 Trait
headers:
  x-cms-transactionId: 
    description: Use for logging and tracking purposes
    type: string 
    required: true
    maxLength: 36
    minLength: 36
    example: "hdsfhjdh-jxbv859-sjdf7643-3746bbdder"
  ClientId:
    required: true
    type: string 
    example: hsdfgysdhfcdshf37er6twgsdhfjcd  
  ClientSecret:
    required: true
    type: string
    example: dsgfhaegur457r6ewsewegrfjesh
          